galaxy_info:
  author: SDDC Team
  description: Inventory vault password change for variables
  company: Red Hat, Inc.

  # https://github.com/AliAkkaya7/ansible-rekey/issues

  license: GNU General Public License v3.0

  min_ansible_version: "2.9"

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  # github_branch:

  # platforms is a list of platforms, and each platform has a name and a list of versions.
  platforms:
    - name: "EL"
      versions:
        - "all"
    - name: Fedora
      versions:
        - "all"

  galaxy_tags:
    - "rekey"
    - "vault"
    - "encrypt"
    - "ansible"
    - "variable"
    - "credential"
    - "aap"

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
