---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer


  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v24.2.2
    hooks:
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: "ansible-lint"
        args:
          - "--profile=production"
        additional_dependencies:
          - "ansible-core>=2.13"
          - "yamllint>=1.26,<2.0"

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
        name: black
        entry: black
        args: [--config=.black.cfg, --check, --diff]
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        types: [python]
