---
- name: Generate a random string to use in the temporary filename
  ansible.builtin.set_fact:
    __rand_string: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
  tags:
    - "aap_vault_change"
    - "aap_post_tasks"

- name: Adding a new vault password to the Temporary Vault file
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/.{{ new_vault_file_name }}_{{ __rand_string }}"
    line: "{{ new_vault_password }}"
    state: present
    create: true
    mode: "0600"
  tags:
    - "aap_vault_change"
    - "aap_post_tasks"
  when:
    - new_vault_password is defined
    - vault_change
