---
- name: Remove temporary vault file
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.{{ new_vault_file_name }}_{{ __rand_string }}"
    state: absent
  tags:
    - "aap_vault_change"
    - "aap_post_tasks"
  when:
    - new_vault_password is defined
    - vault_change
