---
- name: Remove temporary vault file
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.{{ rekey_variable_new_vault_file_name }}_{{ __rand_string }}"
    state: absent
  tags:
    - "aap_vault_change"
    - "aap_post_tasks"
  when:
    - rekey_variable_new_vault_password is defined
    - rekey_variable_vault_change
