name: Build Ansible Collection

on:
    push:
        branches: ["main", "stable", "release/v*", "build_collection"]
    pull_request:
        branches: ["main", "stable", "release/v*", "build_collection"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
#        - name: Set up Python environment
#          run: |
#            sudo apt-get install python3-pip
#            pip install ansible
#        - name: Build collection archive
#          run: ansible-galaxy collection build . --force
#        - name: Upload archive (optional)
#          uses: actions/upload-artifact@v3
#          with:
#            name: collection_archive
#            path: /home/runner/work/ansible_rekey_variables/ansible_rekey_variables/infra-ansible_rekey_variables-1.0.0.tar.gz
#        - name: Get the version name from the tags
#          run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

        - name: Deploy Ansible Galaxy Collection
          uses: artis3n/ansible_galaxy_collection@v2.10.1
          with:
            api_key: '${{ secrets.GALAXY_API_KEY }}'